resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: single-nic-vlans/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: single-nic-vlans/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: single-nic-vlans/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: single-nic-vlans/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: single-nic-vlans/ceph-storage.yaml

parameter_defaults:
  InternalApiNetCidr: 10.16.0.0/24
  TenantNetCidr: 10.17.0.0/24
  StorageNetCidr: 10.18.0.0/24
  StorageMgmtNetCidr: 10.19.0.0/24
  ExternalNetCidr: 10.1.1.0/24
  InternalApiAllocationPools: [{'start': '10.16.0.10', 'end': '10.16.0.200'}]
  TenantAllocationPools: [{'start': '10.17.0.10', 'end': '10.17.0.200'}]
  StorageAllocationPools: [{'start': '10.18.0.10', 'end': '10.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '10.19.0.10', 'end': '10.19.0.200'}]
  # Leave room for floating IPs in the External allocation pool
  ExternalAllocationPools: [{'start': '10.1.1.10', 'end': '10.1.1.50'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 10.1.1.1
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 198.18.53.10
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 198.18.53.10
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["198.18.53.10"]
  InternalApiNetworkVlanID: 20
  StorageNetworkVlanID: 21
  StorageMgmtNetworkVlanID: 22
  TenantNetworkVlanID: 23
  ExternalNetworkVlanID: 10
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "''"
